---
  - name: Update apt cache if needed
    apt: update_cache=yes cache_valid_time=3600

  - name: Upgrade OS
    apt: upgrade=dist force=yes

  - name: Remove components
    apt: pkg={{item}} state=absent purge=yes force=yes
    with_items:
      - wolfram-engine
      - scratch
      - gnome*
      - gvfs*
      - penguinspuzzle
      - lightdm
      - cups*
      - minecraft-pi

  - name: Install needed packages
    apt: pkg={{item}} state=installed
    with_items:
      - autoconf
      - bluez
      - bluez-tools
      - build-essential
      - bundler
      - cmake
      - cron
      - curl
      - emacs
      - gdbserver
      - git
      - git-core
      - glusterfs-server
      - jenkins
      - keepalived
      - libbluetooth-dev
      - libcrypto++-dev
      - libcurl4-openssl-dev
      - libffi-dev
      - libmariadbclient-dev
      - libsqlite3-dev
      - libusb-dev
      - libdbus-1-dev
      - libglib2.0-dev
      - libudev-dev
      - libical-dev
      - libreadline-dev
      - libssl-dev
      - libxml2-dev
      - libxslt1-dev
      - libyaml-dev
      - logrotate
      - netatalk
      - nginx
      - oracle-java8-jdk
      - pmount
      - rfkill
      - smbclient
      - samba
      - samba-common-bin
      - screen
      - sqlite3
      - tmux
      - ufw
      - uuid-dev
      - vim
      - xrdp
      - xvfb
      - xz-utils
      - zlib1g-dev

#First I added the key for the LTS version to my repository
#
#wget -q -O - http://pkg.jenkins-ci.org/debian-stable/jenkins-ci.org.key | sudo apt-key add -
#Then I updated /etc/apt/sources.list: adding this line to the top of the file
#
#deb http://pkg.jenkins-ci.org/debian-stable binary/
#Updated the local package index, then finally install Jenkins:
#
#sudo apt-get update
#sudo apt-get install jenkins

  - name: Check if anything needs autoremoving
    shell: apt-get -y --dry-run autoremove | grep -q "0 to remove"
    register: check_autoremove
    ignore_errors: True
    changed_when: False
    check_mode: no

  - name: Autoremove unused packages
    command: apt-get -y autoremove
    when: "check_autoremove.rc != 0"

  - name: FW Allow everything
    ufw: state=enabled policy=allow

  - name: UFW allow SSH
    ufw: rule=allow name={{item}}
    with_items:
      - OpenSSH

  - name: Create a user
    user: name={{item}} comment="A user" generate_ssh_key=yes ssh_key_bits=2048 state=present password={{password}} shell=/bin/bash
    with_items:
      - "{{user}}"

  - name: Set up ssh config file
    copy: src=ssh_config dest=/home/{{item}}/.ssh/config owner={{item}}
    with_items:
      - "{{user}}"

  - name: Copy ssh keys to the user's .ssh directory
    copy: src=ita.pub dest=/home/{{item}}/.ssh/authorized_keys mode=0700 owner={{item}} group={{item}}
    with_items:
      - "{{user}}"

  - name: Set {{user}} as sudoer
    lineinfile: dest=/etc/sudoers line="{{item}} ALL=(ALL) NOPASSWD:ALL"
    with_items:
      - "{{user}}"

  - name: Set vi preferences
    copy: src=vimrc dest=/home/{{item}}/.vimrc owner={{item}}
    with_items:
      - "{{user}}"

  - name: Set bash preferences
    copy: src=bash_profile dest=/home/{{item}}/.bash_profile owner={{item}}
    with_items:
      - "{{user}}"

  - name: Set git preferences
    copy: src=gitconfig dest=/home/{{item}}/.gitconfig owner={{item}}
    with_items:
      - "{{user}}"

  - name: Set git ignore
    copy: src=gitignore dest=/home/{{item}}/.gitignore_global owner={{item}}
    with_items:
      - "{{user}}"

  - name: Make sure user is part of plugdev
    user: name={{item}} groups="plugdev"
    with_items:
      - "{{user}}"

  - name: Copy bitbucket ssh keys to the user's .ssh directory
    copy: src=~/.ssh/id_rsa_bitbucket dest=/home/{{item}}/.ssh/id_rsa_bitbucket
    with_items:
      - "{{user}}"

  - name: Copy github ssh keys to the user's .ssh directory
    copy: src=~/.ssh/id_rsa dest=/home/{{item}}/.ssh/id_rsa_github
    with_items:
      - "{{user}}"

  - name: Set up samba sharing
    action: template src=smb.conf dest=/etc/samba
    notify: Restart samba
